---
abstract: Logs the time elapsed between the last log event
author: 'Emmanuel Rodriguez, <emmanuel.rodriguez@gmail.com>.'
build_requires:
  Log::Log4perl::Appender::TestBuffer: 0
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Log-Log4perl-Layout-PatternLayout-Elapsed
no_index:
  directory:
    - inc
    - t
recommends:
  Time::HiRes: 0
requires:
  Log::Log4perl::Layout::PatternLayout: 0
  perl: 5.6.0
version: 0.01
